### ISSUE TITLE
Next TC meeting invitation

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#10]
I was wondering and wanted just to confirm with you for agreement, how we should go about the invitation for the next TC telecon?

1. Where should we announce? 
* I suggest OpenPlanetary, but even there's the question, in the general channel, or the #planetarypy channel only? It could create quite a different response?
* Other channels, should we go as public as Twitter? Not that I have many readers, but if OpenPlanetary retweets it, it might get quite some resonance. Do we want that much resonance?

2. Should be formulate an email in addition, or as the sole invitation channel, by addressing candidates directly? Should we then agree on a list of candidates?

**Comment by rbeyer** [comment]
I think you should determine a date and a time amongst those that have already shown interest, and then advertise that meeting to anyone that wants to attend, via any and all means that you indicate above.  I think it is important to note when you do so, that this is really for Python developers who plan to help architect the PlanetaryPy project, not end-users of `planetarypy`.

You talk about 'candidates', but 'candidates' for what, are we having an election?

I think our TC meetings should be considered open, and all are welcome to attend. Once my PR gets merged, then the TC will also have rules for membership.  Anyone can attend a meeting, and anyone can ask to join the TC if they want, or not!  I think the emphasis should be less on a formal membership list, and more on determining what needs to be done and how to do it.  Formal membership on the TC is almost irrelevant, what we want are people participating now in making decisions, and later in contributing code.

**Comment by michaelaye** [comment]
Candidates of wanting to be part of TC?

**Comment by michaelaye** [comment]
I somehow remember that we didn't have free open meetings at PSO, did we?

**Comment by rbeyer** [comment]
That's a good point, I just looked at the draft Charter.  The only language in the 'Meetings' section about attendance at TC meetings is:

> The TC may invite persons or representatives from outside of the TC to participate in a non-voting capacity.

One could certainly get the implication from this one sentence that if you were *not* invited by the TC, that you would not be welcome.  However, based on all of the other tenets in the Charter about inclusivity, I don't think this is the correct interpretation.  I think it is: the TC may go and explicitly ask people to join a particular meeting that may not otherwise do so in order to solicit information or advice (kind of a 'request to speak' invitation).

If we interpret that sentence that way, there is no mention of a limited attendance at TC meetings in the PSO Charter (or our draft charter).

Also, the README in the PSO Meetings directly explicitly says:

> All are welcome to attend our meetings!

I think that's a good model.

**Comment by rbeyer** [comment]
> Candidates of wanting to be part of TC?

That's what I thought you meant, and I'm sorry for teasing.  Let me address your question directly:

> Should be formulate an email in addition, or as the sole invitation channel, by addressing candidates directly? Should we then agree on a list of candidates?

No, I don't think so.  I don't think we need to take any special action in order to 'grow' the TC.  Once the 'governance' PR gets merged, we'll have rules for how to add people to the TC if they wish to be added, but I think having open TC meetings, and focusing on the 'work' that we need to do will generate interest (and hopefully contributions), and then some subset of that group will ask to join the TC, but I think it is secondary to moving things forward.

**Comment by michaelaye** [comment]
Your teasing brought to light a confusion on my side though, between TC meeting attendance and TC membership, so that's okay. Will create a doodle poll now for current indicated members.

**Comment by rbeyer** [comment]
I think this Issue is satisfied now?  Michael?

**Comment by michaelaye** [comment]
indeed, thanks!
