### ISSUE TITLE
Create cookiecutter template

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#16]
As Ross correctly identified, it makes more sense to start with a fresh clone from the best fitting cookiecutter repositories, because their creators kept those up-to-date with more modern (as compared 5 years ago) requirements, instead of updating all files in the old one that's here in planetarypy.

These are the things that should be established by the template:

- [x] Python versions supported 3.6/3.7
- [x] Pypi deployment
- [ ] Ideally, conda package templating (might be just a stump but not automatically activated)
- [x] Test directory outside installed package
- [x] Sphinx documentation with appropriate plugins
- [x] ReadTheDocs settings file
- [ ] Code coverage configuration (which service do we want to use?
- [x] Pytest example skeleton file
- [x] Setup.py or dephell configuration file

Add more points to this list if you think there's missing something.

Next step is to identify the best cookiecutter repo to start with. I'll check if there's already one using the tox-conda plugin.

**Comment by rbeyer** [comment]
I got impatient, and just started: https://github.com/planetarypy/package-template

I just straight-up forked the audreyr/cookiecutter-pypackage.  Then I mirrored the changes in https://github.com/planetarypy/cookiecutter-pypackage, and added some others that we had talked about.

There is still a ton to do, but I often find that we sometimes put too much emphasis on waiting to start, so I just got started.

**Comment by rbeyer** [comment]
So I checked off the items in the original issue at the top that I think are addressed.  I couldn't find a cookie-cutter that was using the tox-conda plugin that Michael was talking about, but we can always add it.

So the 'coverage' package is being used in the template now, which allows you to do `make coverage` not sure what you had in mind for a service?

Also not sure how to do 'conda package templating' since a conda-forge recipe would be outside the repo itself.  Maybe you're talking about an example .yml file?  I think maybe the better thing to do is just include some instructions that point to the conda-forge instructions.  That way we don't have to worry about tracking the upstream conda-forge instructions ourselves, which is why I suspect that cookiecutter doesn't include it.

**Comment by michaelaye** [comment]
should we discuss issues and pull request for the package-template in its own repo and close this issue?

**Comment by rbeyer** [comment]
That would be fine with me.
