### ISSUE TITLE
What License shall we use?

### ISSUE THREAD

**Issue by rbeyer** [planetarypy/TC#2]
Most of the code in the planetarypy org has a BSD-3-Clause license.

The Astropy project also uses a BSD-3-Clause license.  Looks like Andrew has SpiceyPy under an MIT license, and since ASP has an Apache2 license, that's my typical go-to.

What should we use for PlanetaryPy going forward?

**Comment by AndrewAnnex** [comment]
Apache2 is probably the way to go for this

**Comment by rbeyer** [comment]
I'll be honest, I wasn't expecting that (just given your project licensing history).  Why do you think the Apache2 license is the way to go?  

I spent some time this weekend doing some reading on the licenses (which I hadn't done in a while), and I'm still not sure which I'd favor for PlanetaryPy.  The good thing is that if we go with one of these three, anything that is licensed under MIT (like SpiceyPy) or BSD-3-Clause (like the existing GitHub planetarypy projects) can be relicensed under any one of those three, they're compatible.

**Comment by AndrewAnnex** [comment]
apache is "safer" if you anticipate a lot of different organizations and users contributing back to the codebase because it is more wordy than MIT. SpiceyPy is MIT because I didn't anticipate anyone contributing back at the start and I just wanted something simple. BSD I know less about, I know a lot of projects use it so maybe it is somewhere in between MIT and Apache 2 (https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences). There are also some "[issues](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html)" with MIT, IANAL but my understanding is that BSD-3 and Apache 2 are more explicit about the terms of the license and some other areas like patents that MIT does not discuss. I don't think there is any downsides to Apache 2 for a project like this, other than it might confuse folks new to open source contributing, alternatively, companies and other orgs may be happier with apache 2 license. There are plenty of Apache 2 projects out there, so that first concern is fairly minor to me

**Comment by michaelaye** [comment]
I'd prefer similarity with astropy here, b/c their history has shown that their license does **NOT** create problems with applying for external funds and having a large contributing user-base. And I don't think we ever would need any more or different collaboration (or "kind of collaboration) than the astropy project currently receives?

**Comment by AndrewAnnex** [comment]
I’m okay with BSD-3, there are very academic arguments to make for one over the other but it is mostly splitting hairs and it really depends on priorities. 

-Andrew Annex

**Comment by rbeyer** [comment]
I actually think that Andrew's comment above is about right.  The Apache2 license is more loved by legal departments because it is very explicit and careful.  My experience is that large companies or organizations tend to release stuff under Apache2 because of this explicitness.  The BSD-3-Clause is very simple and straightforward, less intimidating to the causal contributor, as Andrew points out.

To Michael's point, none of the licenses we're talking about would impair or hamper any funding source that I'm aware of from funding developers to contribute to the codebase.  That, at least, is a non-issue.

There's certainly something to be said for using BSD-3-Clause, to mirror Astropy.  Does anybody have any insight into what motivated their selection?  It would be good to know the history of their decision-making process.

**Comment by rbeyer** [comment]
At our meeting today, we agreed to use the BSD-3-Clause license for the PlanetaryPy project.
