### ISSUE TITLE
icons on affiliated packages page seem broken

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#74]
On this page:

https://planetarypy.org/packages/

![image](https://user-images.githubusercontent.com/69774/155191108-60c858a3-92ff-4c46-9ddd-ecf749da55d1.png)

**Comment by rbeyer** [comment]
Indeed, they were broken because we were just linking to a graphic at PyPI whose name apparently changed on their side.  To fix that, I've now just made a local copy that we staticly serve.

FYI Issues with the web site should probably go to its repo at https://github.com/planetarypy/planetarypy.github.io/issues/new not to Issues on the TC repo.
